version: '3.8'

services:
  web:
    build: .
    command: python3 manage.py migrate && python3 manage.py collectstatic --no-input --clear && gunicorn qmra.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./qmra.db/:/qmra/qmra.db
    ports:
      - 8000:8000