version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput --clear &&
             python manage.py migrate &&
             gunicorn qmra.wsgi:application --bind 0.0.0.0:8080"
    volumes:
      - ./qmra.db/:/qmra/qmra.db
      - /var/cache/qmra/static:/var/cache/qmra/static
    ports:
      - 8080:8080