from django.urls import path, include
from qmra.risk_assessment import views


urlpatterns = [
    path(
        "assessments",
        views.list_risk_assessment_view,
        name="assessments",
    ),
    path(
        "assessment",
        views.risk_assessment_view,
        name="assessment",
    ),
    path(
        "assessment/<uuid:risk_assessment_id>",
        views.risk_assessment_view,
        name="assessment",
    ),
    path(
        "assessment/<uuid:risk_assessment_id>/results",
        views.risk_assessment_result,
        name="assessment-result",
    ),
    path(
        "assessment/<uuid:risk_assessment_id>/export",
        views.export_risk_assessment,
        name="assessment-export",
    ),
    path(
        "assessment/results",
        views.risk_assessment_result,
        name="assessment-result",
    ),
    path(
        "exposure",
        views.create_exposure,
        name="exposure"
    ),
    path(
        "exposures",
        views.list_exposures,
        name="exposures"
    ),
    path(
        "source",
        views.create_source,
        name="source"
    ),
    path(
        "sources",
        views.list_sources,
        name="sources"
    ),
    path(
        "inflows",
        views.list_inflows,
        name="inflows"
    ),
    path(
        "treatment",
        views.create_treatment,
        name="treatment"
    ),
    path(
        "treatments",
        views.list_treatments,
        name="treatments"
    ),
    path('', include('django_prometheus.urls')),
]