# Generated by Django 5.0.6 on 2024-10-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='pathogen',
            field=models.CharField(choices=[('', '---------'), ('Bacteria', [('Campylobacter jejuni', 'Campylobacter jejuni')]), ('Viruses', [('Rotavirus', 'Rotavirus')]), ('Protozoa', [('Cryptosporidium parvum', 'Cryptosporidium parvum')])], max_length=256),
        ),
        migrations.AlterField(
            model_name='riskassessmentresult',
            name='dalys_risk',
            field=models.CharField(choices=[('min', 'min'), ('max', 'max'), ('none', 'none')], max_length=4),
        ),
        migrations.AlterField(
            model_name='riskassessmentresult',
            name='infection_risk',
            field=models.CharField(choices=[('min', 'min'), ('max', 'max'), ('none', 'none')], max_length=4),
        ),
        migrations.AlterField(
            model_name='riskassessmentresult',
            name='pathogen',
            field=models.CharField(choices=[('', '---------'), ('Bacteria', [('Campylobacter jejuni', 'Campylobacter jejuni')]), ('Viruses', [('Rotavirus', 'Rotavirus')]), ('Protozoa', [('Cryptosporidium parvum', 'Cryptosporidium parvum')])], max_length=256),
        ),
    ]
