# Generated by Django 5.0.6 on 2025-02-05 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0002_alter_inflow_pathogen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExposure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('events_per_year', models.IntegerField()),
                ('volume_per_event', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=64)),
                ('rotavirus_min', models.FloatField(blank=True, null=True)),
                ('rotavirus_max', models.FloatField(blank=True, null=True)),
                ('campylobacter_min', models.FloatField(blank=True, null=True)),
                ('campylobacter_max', models.FloatField(blank=True, null=True)),
                ('cryptosporidium_min', models.FloatField(blank=True, null=True)),
                ('cryptosporidium_max', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTreatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=64)),
                ('bacteria_min', models.FloatField(blank=True, null=True)),
                ('bacteria_max', models.FloatField(blank=True, null=True)),
                ('viruses_min', models.FloatField(blank=True, null=True)),
                ('viruses_max', models.FloatField(blank=True, null=True)),
                ('protozoa_min', models.FloatField(blank=True, null=True)),
                ('protozoa_max', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
