# Generated by Django 5.0.6 on 2025-02-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0003_userexposure_usersource_usertreatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='exposure_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='source_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userexposure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
