# Generated by Django 5.0.6 on 2025-02-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0004_alter_riskassessment_exposure_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='train_index',
            field=models.IntegerField(default=0),
        ),
    ]
