# Generated by Django 5.0.6 on 2025-09-17 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0005_treatment_train_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='QMRAPathogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Bacteria', 'Bacteria'), ('Viruses', 'Viruses'), ('Protozoa', 'Protozoa')], max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('best_fit_model', models.CharField(choices=[('exponential', 'exponential'), ('beta-Poisson', 'beta-Poisson')], max_length=256)),
                ('k', models.FloatField(blank=True, null=True)),
                ('alpha', models.FloatField(blank=True, null=True)),
                ('n50', models.FloatField(blank=True, null=True)),
                ('infection_to_illness', models.FloatField(blank=True, default=True, null=True)),
                ('dalys_per_case', models.FloatField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QMRAReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.URLField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='QMRASource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='QMRAExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('events_per_year', models.IntegerField()),
                ('volume_per_event', models.FloatField()),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_assessment.qmrareference')),
            ],
        ),
        migrations.CreateModel(
            name='QMRAInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_assessment.qmrapathogen')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_assessment.qmrareference')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_assessment.qmrasource')),
            ],
        ),
        migrations.CreateModel(
            name='QMRATreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('group', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('bacteria_min', models.FloatField(blank=True, null=True)),
                ('bacteria_max', models.FloatField(blank=True, null=True)),
                ('viruses_min', models.FloatField(blank=True, null=True)),
                ('viruses_max', models.FloatField(blank=True, null=True)),
                ('protozoa_min', models.FloatField(blank=True, null=True)),
                ('protozoa_max', models.FloatField(blank=True, null=True)),
                ('bacteria_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bacteria_lrv', to='risk_assessment.qmrareference')),
                ('protozoa_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protozoa_lrv', to='risk_assessment.qmrareference')),
                ('viruses_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viruses_lrv', to='risk_assessment.qmrareference')),
            ],
        ),
    ]
