# Generated by Django 5.0.6 on 2026-01-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0006_qmrapathogen_qmrareference_qmrasource_qmraexposure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmratreatment',
            name='bacteria_references',
            field=models.ManyToManyField(related_name='bacteria_lrvs', to='risk_assessment.qmrareference'),
        ),
        migrations.AddField(
            model_name='qmratreatment',
            name='protozoa_references',
            field=models.ManyToManyField(related_name='protozoa_lrvs', to='risk_assessment.qmrareference'),
        ),
        migrations.AddField(
            model_name='qmratreatment',
            name='viruses_references',
            field=models.ManyToManyField(related_name='viruses_lrvs', to='risk_assessment.qmrareference'),
        ),
    ]
