# Generated by Django 5.0.6 on 2026-01-15 12:42

from django.db import migrations


def migrate_references(apps, schema_editor):
    if schema_editor.connection.alias != "qmra":
        return
    QMRATreatment = apps.get_model("risk_assessment", "QMRATreatment")
    for treatment in QMRATreatment.objects.all():

        treatment.bacteria_references.add(treatment.bacteria_reference)
        treatment.viruses_references.add(treatment.viruses_reference)
        treatment.protozoa_references.add(treatment.protozoa_reference)


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0007_qmratreatment_bacteria_references_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_references),
    ]
