# Generated by Django 5.0.6 on 2026-01-15 12:42
from django.core.management import call_command
from django.db import migrations


def migrate_references(apps, schema_editor):
    if schema_editor.connection.alias != "qmra":
        return
    QMRATreatment = apps.get_model("risk_assessment", "QMRATreatment")
    all_treatments = QMRATreatment.objects.all()
    if len(all_treatments) == 0:
        call_command("seed_default_db")
        all_treatments = QMRATreatment.objects.all()
    for treatment in all_treatments:

        treatment.bacteria_references.add(treatment.bacteria_reference)
        treatment.viruses_references.add(treatment.viruses_reference)
        treatment.protozoa_references.add(treatment.protozoa_reference)
        treatment.save()
    call_command("export_default")


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0008_auto_20260115_1342'),
    ]

    operations = [
        migrations.RunPython(migrate_references),
    ]
