# Generated by Django 5.0.6 on 2026-01-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0009_auto_20260121_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qmratreatment',
            name='bacteria_reference',
        ),
        migrations.RemoveField(
            model_name='qmratreatment',
            name='protozoa_reference',
        ),
        migrations.RemoveField(
            model_name='qmratreatment',
            name='viruses_reference',
        ),
    ]
