# Generated by Django 5.0.14 on 2026-09-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0010_remove_qmratreatment_bacteria_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='failure_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='failure_frequency',
            field=models.FloatField(default=0),
        ),
    ]
