# Generated by Django 5.0.14 on 2026-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0010_remove_qmratreatment_bacteria_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmratreatment',
            name='failure_duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='qmratreatment',
            name='failure_frequency_days_per_year',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='treatment',
            name='failure_duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='failure_frequency_days_per_year',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertreatment',
            name='failure_duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='usertreatment',
            name='failure_frequency_days_per_year',
            field=models.FloatField(default=0),
        ),
    ]
