# Generated by Django 5.0.14 on 2026-09-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0011_treatment_failure_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertreatment',
            name='failure_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='usertreatment',
            name='failure_frequency',
            field=models.FloatField(default=0),
        ),
    ]
