apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "app.fullname" . }}-static-files-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: {{ .Values.static.hostpath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "app.fullname" . }}-sqlite-file-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: {{ .Values.sqlite.hostpath }}
    type: FileOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-static-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: {{ include "app.fullname" . }}-static-files-pv
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-sqlite-file-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: {{ include "app.fullname" . }}-sqlite-file-pv
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath