---
name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Declare image's tag
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: qmra:${{ env.sha_short }}
          load: true
      - name: Save
        run: docker save qmra > img.tar
      - name: Push
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          source: "img.tar"
          target: ${{ secrets.DEPLOY_PATH }}