---
name: Deploy Django Application

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
     
    - name: Install rsync and configure SSH
      run: |
        sudo apt-get install -y rsync
        echo "${{ secrets.DEPLOY_SERVER_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to remote server
      env:
        REMOTE_HOST: qmra.org
        REMOTE_USER: wseis
        REMOTE_DIR: /opt/qmra
      run: |
        rsync -avz --delete --exclude '.git' --exclude 'private_key.pem' -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./ ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:${{ env.REMOTE_DIR }}
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} "\
        
        cd ${REMOTE_DIR} && sudo pkill gunicorn && source /var/opt/qmra/miniconda3/bin/activate qmra && \ 
        cd tools && export PYTHONPATH=/etc/opt/qmra:/opt/qmra/tools && export DJANGO_SETTINGS_MODULE=settings && \
        gunicon tools.wsgi:application 
