---
name: Deploy Django Application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }} && git pull
          microk8s ctr image import img.tar && rm img.tar
          cd infra/helm
          microk8s helm upgrade -f ${{ inputs.environment }}.values.yaml qmra ./qmra -n qmra --set app_secret_key.value=${{ secrets.APP_SECRET_KEY }},image.tag=${{ env.sha_short }}