---
name: Deploy Django Application

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
     
    - name: Install and configure SSH
      run: |
        echo "${{ secrets.DEPLOY_SERVER_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to remote server
      env:
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_DIR: ${{ secrets.DEPLOY_PATH }}
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} "\
        sudo docker compose down || true
        cd ${{ env.REMOTE_DIR }} && bash infra/deployment_scripts/04_deploy_latest.sh"