---
name: Deploy Django Application

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build    
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        tags: qmra:local
        outputs: type=local,dest=- > ./img.tar
    - name: Save
      run: docker save qmra > img.tar
    - name: Push
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
        source: "img.tar"
        target: ${{ secrets.DEPLOY_PATH }}
    - name: Deploy
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }} && git pull
          microk8s ctr image import img.tar && rm img.tar
          cd infra/helm
          microk8s helm upgrade qmra ./qmra -n qmra --set app_secret_key.value=${{ secrets.APP_SECRET_KEY }}